name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.24'
          cache-dependency-path: core/go.sum

      - name: Test Core
        run: |
          cd core
          go test -race -v -coverprofile=coverage.txt ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.24'

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
